:logfile: ./log/sidekiq.log
development:
  :concurrency: 25
  :queues:
    - mailers
    - exports
staging:
  :concurrency: 25
  :queues:
    - mailers
    - exports
production:
  :concurrency: 2
  :queues:
    - mailers
    - exports
